# .github/workflows/deploy.yml
name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      env:
        CONNECTION_STRING : ${{ secrets.CONNECTION_STRING }}
        JWT_ACCESS_TOKEN_SECRET : ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
        JWT_RESET_TOKEN_SECRET : ${{ secrets.JWT_RESET_TOKEN_SECRET }}
        JWT_AUDIENCE : ${{ secrets.JWT_AUDIENCE }}
        JWT_ISSUER : ${{ secrets.JWT_ISSUER }}
        JWT_ACCESS_TOKEN_EXPIRES : ${{ secrets.JWT_ACCESS_TOKEN_EXPIRES }}
        JWT_RESET_TOKEN_EXPIRES : ${{ secrets.JWT_RESET_TOKEN_EXPIRES }}
      run: |
        docker build -t ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest .
        docker push ${{ secrets.REGISTRY }}/coffee:latest

    - name: SSH into the server and pull the latest Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest
          docker stop ${{ secrets.DOCKER_CONTAINER }} || true
          docker rm ${{ secrets.DOCKER_CONTAINER }} || true
          docker run -d --name coffee_container -p 80:80 ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest
