# .github/workflows/deploy.yml
name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest .
        docker push ${{ secrets.REGISTRY }}/coffee:latest

    - name: SSH into the server and pull the latest Docker image
      uses: appleboy/ssh-action@master
      with:
        host: your_server_ip
        username: your_ssh_username
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          ssh-keyscan your_server_ip >> ~/.ssh/known_hosts
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest
          docker stop ${{ secrets.DOCKER_CONTAINER }} || true
          docker rm ${{ secrets.DOCKER_CONTAINER }} || true
          docker run -d --name coffee_container -p 5000:80 ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest
